# Site settings
title: PanWriter
descriptipn: Markdown editor with pandoc integration and paginated preview
url: https://panwriter.com
githubUsername: mb21

# see https://github.com/github/jekyll-commonmark-ghpages
markdown: CommonMarkGhPages
commonmark:
  extensions: ["table"]

# Build settings
permalink: pretty
